/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal installs. It is checked in here
// because the project was scaffolded manually on a machine where Node is blocked.
